import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { currentUser } from "@clerk/nextjs/server";

export async function POST(request: Request) {
  try {
    const user = await currentUser();
    if (!user)
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const body = await request.json();
    const yt_channel_id: string | undefined = body?.yt_channel_id;
    if (!yt_channel_id) {
      return NextResponse.json(
        { error: "yt_channel_id is required" },
        { status: 400 }
      );
    }

    // Validate channel belongs to user
    const owner = await prisma.channels.findUnique({
      where: {
        userId_channelId: { userId: user.id, channelId: yt_channel_id },
      },
      select: { channelId: true },
    });
    if (!owner) {
      return NextResponse.json(
        { error: "Channel not found for current user" },
        { status: 404 }
      );
    }

    const agentBase = process.env.SMYTHOS_AGENT2;
    if (!agentBase) {
      return NextResponse.json(
        { error: "SMYTHOS_AGENT2 is not configured" },
        { status: 500 }
      );
    }

    // Backend inserts a placeholder query automatically
    const payload = {
      query:
        "auto-generated by backend: overall content gap analysis for the channel",
      yt_channel_id,
    } as const;

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 120_000);
    let resp: Response;
    try {
      resp = await fetch(agentBase + "/Auto_Gap_Finder", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },
        body: JSON.stringify(payload),
        signal: controller.signal,
      });
    } finally {
      clearTimeout(timeout);
    }

    const data = await resp.json().catch(() => ({}));
    if (!resp.ok) {
      return NextResponse.json(
        { error: "External agent error", details: data },
        { status: 502 }
      );
    }

    const content_gaps = data?.result?.Output?.content_gaps || [];
    const opportunities = data?.result?.Output?.opportunities || [];
    return NextResponse.json({ content_gaps, opportunities });
  } catch (error) {
    console.error("/api/channels/gaps/overall error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
